import { writeFile } from 'node:fs/promises';

const covers = Object.freeze({
  Cinema: [
    'https://images.unsplash.com/photo-1751823886813-0cfc86cb9478?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1729006426245-b774fc155c1e?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1517486518908-97a5f91b325f?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=82',
  ],
  'TV & Séries': [
    'https://images.unsplash.com/photo-1478802848783-2ed6e96a0462?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1615986200762-a1ed9610d3b1?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1593784991188-c899ca07263b?auto=format&fit=crop&w=1200&q=82',
  ],
  Livros: [
    'https://images.unsplash.com/photo-1763368230845-150be8503232?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1754430543609-aae159c530ef?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1752920299211-28be8c9b0121?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1772617616232-b9ed723ab115?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1750809411151-c46ca3d43b97?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1520467795206-62e33627e6ce?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1567168539593-59673ababaae?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1765634898266-6bd03cb0fce7?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1760106782590-bb02f861cbc7?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1769962929240-24f4c2a69b3b?auto=format&fit=crop&w=1200&q=82',
  ],
  Arte: [
    'https://images.unsplash.com/photo-1774125553858-3f41e84d4e92?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1766289496983-ea3c8127f27f?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1769905226750-1db769c30bdc?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1772617616268-a2f27d194fce?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1695922294859-925ffd18a4e6?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1779070693953-5a2f9207a140?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1742146861179-a1f7cc547e3d?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1785290515822-2cf15f4cc6db?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1747766369281-26a375aadf6d?auto=format&fit=crop&w=1200&q=82',
  ],
  Moda: [
    'https://images.unsplash.com/photo-1784850227098-d731ad18cf02?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1784850758009-2b41bcf1f242?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1784850350622-701c3053f0ae?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1784850350833-ebf69e760d0b?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1784850758006-21742e6553ad?auto=format&fit=crop&w=1200&q=82',
  ],
  Famosos: [
    'https://images.unsplash.com/photo-1731007733979-6f3d7b8632ae?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1704253802932-61137bd11d07?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1657412235086-c2de1a1176a9?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1774301786017-a9ac4a74e6f2?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1786552428640-da953178d0ce?auto=format&fit=crop&w=1200&q=82',
  ],
  Natureza: [
    'https://images.unsplash.com/photo-1723965849654-a36fe740cab0?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1782848796142-88a50598df91?auto=format&fit=crop&w=1200&q=82',
  ],
  Motores: [
    'https://images.unsplash.com/photo-1785103336655-8f69d35957f3?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1675065720352-f3a5fac5b179?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1787310725110-932df03f7c9f?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1711476926864-5cbbe34f0f5e?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1785186128382-82aff2b57bbd?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1785498491915-d535dddc97b7?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=82',
  ],
  Jogos: [
    'https://images.unsplash.com/photo-1632765743329-3b257fe779a6?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1760900954419-89f057caf7f2?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1655029164758-51e484f5576b?auto=format&fit=crop&w=1200&q=82',
  ],
  Tecnologia: [
    'https://images.unsplash.com/photo-1779011654250-f1100196a5e0?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1761906976176-0559a6d130dd?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1772618375204-06b8348417e5?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1784969330482-edd995d4edec?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1783419116339-a2956ffeb7a0?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1688895463871-f5e81079d7be?auto=format&fit=crop&w=1200&q=82',
  ],
  Produtos: [
    'https://images.unsplash.com/photo-1781232815711-1c1d9ec1ca44?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1786617829002-e130d77fe64a?auto=format&fit=crop&w=1200&q=82',
    'https://images.unsplash.com/photo-1606021490433-d28d1d978deb?auto=format&fit=crop&w=1200&q=82',
  ],
});

const coverIndexes = new Map();

function ranking(id, category, question, focus, options) {
  const index = coverIndexes.get(category) || 0;
  coverIndexes.set(category, index + 1);
  return { id, category, question, focus, options, image: covers[category]?.[index] };
}

const definitions = [
  ranking(
    'comedias-cinema',
    'Cinema',
    'Qual é a melhor comédia de todos os tempos?',
    'Comédia pode nascer de diálogo, absurdo, constrangimento, sátira ou pura confusão, e os filmes mais fortes continuam engraçados mesmo depois de muitas revisões.',
    [
      'O Auto da Compadecida',
      'Minha Mãe É uma Peça',
      'Apertem os Cintos... O Piloto Sumiu!',
      'Feitiço do Tempo',
      'Quanto Mais Quente Melhor',
      'Monty Python em Busca do Cálice Sagrado',
      'A Vida de Brian',
      'O Grande Lebowski',
      'Se Beber, Não Case!',
      'Missão Madrinha de Casamento',
      'Superbad: É Hoje',
      'Um Príncipe em Nova York',
      'Curtindo a Vida Adoidado',
      'Harry e Sally: Feitos um para o Outro',
      'Tempos Modernos',
      'Luzes da Cidade',
      'O Grande Hotel Budapeste',
      'Os Caça-Fantasmas',
      'Tootsie',
      'Dr. Fantástico',
    ],
  ),
  ranking(
    'animacoes-cinema',
    'Cinema',
    'Qual é a melhor animação da história do cinema?',
    'Animação não é um gênero único: ela atravessa aventura, drama, humor, fantasia e experimentação visual em filmes feitos para públicos de todas as idades.',
    [
      'Toy Story',
      'A Viagem de Chihiro',
      'O Rei Leão',
      'Shrek',
      'WALL-E',
      'Ratatouille',
      'Up: Altas Aventuras',
      'Divertida Mente',
      'Homem-Aranha no Aranhaverso',
      'Princesa Mononoke',
      'Túmulo dos Vagalumes',
      'A Bela e a Fera',
      'Os Incríveis',
      'Procurando Nemo',
      'Viva: A Vida é uma Festa',
      'O Fantástico Sr. Raposo',
      'Akira',
      'O Gigante de Ferro',
      'Pinóquio',
      'Branca de Neve e os Sete Anões',
    ],
  ),
  ranking(
    'filmes-ficcao-cientifica',
    'Cinema',
    'Qual é o maior filme de ficção científica?',
    'A melhor ficção científica usa futuro, tecnologia, espaço e mundos alternativos para falar também de medo, poder, identidade e do destino da humanidade.',
    [
      '2001: Uma Odisseia no Espaço',
      'Blade Runner: O Caçador de Androides',
      'Matrix',
      'Alien: O Oitavo Passageiro',
      'O Exterminador do Futuro 2',
      'Star Wars: O Império Contra-Ataca',
      'Interestelar',
      'De Volta para o Futuro',
      'A Chegada',
      'Jurassic Park',
      'E.T.: O Extraterrestre',
      'A Origem',
      'Solaris',
      'Filhos da Esperança',
      'Mad Max: Estrada da Fúria',
      'Duna: Parte Dois',
      'O Enigma de Outro Mundo',
      'Distrito 9',
      'Ex Machina',
      'O Planeta dos Macacos',
    ],
  ),
  ranking(
    'viloes-cinema',
    'Cinema',
    'Qual vilão do cinema é impossível esquecer?',
    'Os grandes vilões podem assustar, seduzir, provocar ou dominar uma história inteira com poucos minutos de tela, deixando frases e imagens que sobrevivem ao próprio filme.',
    [
      'Darth Vader',
      'Hannibal Lecter',
      'Coringa em O Cavaleiro das Trevas',
      'Anton Chigurh',
      'Norman Bates',
      'Lord Voldemort',
      'Enfermeira Ratched',
      'T-1000',
      'Agente Smith',
      'Thanos',
      'Bruxa Má do Oeste',
      'Hans Landa',
      'Scar',
      'Sauron',
      'Freddy Krueger',
      'Michael Myers',
      'Jason Voorhees',
      'Annie Wilkes',
      'Cômodo',
      'Cruella de Vil',
    ],
  ),
  ranking(
    'finais-cinema',
    'Cinema',
    'Qual filme tem o final mais inesquecível?',
    'Um grande final pode virar toda a história, fechar uma jornada com emoção ou deixar uma pergunta que continua acompanhando o público muito depois dos créditos.',
    [
      'O Sexto Sentido',
      'Clube da Luta',
      'O Planeta dos Macacos',
      'Os Suspeitos',
      'Seven: Os Sete Crimes Capitais',
      'Cinema Paradiso',
      'Casablanca',
      'Whiplash: Em Busca da Perfeição',
      'A Origem',
      'O Nevoeiro',
      'Oldboy',
      'A Primeira Noite de um Homem',
      '2001: Uma Odisseia no Espaço',
      'Thelma & Louise',
      'Toy Story 3',
      'A Chegada',
      'Memórias de um Assassino',
      'Parasita',
      'Ilha do Medo',
      'Brazil: O Filme',
    ],
  ),
  ranking(
    'novelas-brasileiras',
    'TV & Séries',
    'Qual é a maior novela brasileira de todos os tempos?',
    'Novelas brasileiras transformaram personagens, bordões, trilhas e grandes conflitos em memória coletiva, atravessando horários, emissoras e gerações.',
    [
      'Roque Santeiro',
      'Vale Tudo',
      'Avenida Brasil',
      'Pantanal (1990)',
      'O Clone',
      'Tieta',
      'A Próxima Vítima',
      'Mulheres de Areia',
      'Senhora do Destino',
      'Renascer (1993)',
      'Terra Nostra',
      'Por Amor',
      'Laços de Família',
      'O Rei do Gado',
      'Gabriela (1975)',
      'Escrava Isaura (1976)',
      'Que Rei Sou Eu?',
      'Vamp',
      'Xica da Silva',
      'Chocolate com Pimenta',
    ],
  ),
  ranking(
    'series-comedia',
    'TV & Séries',
    'Qual é a melhor série de comédia?',
    'Sitcoms, comédias dramáticas e sátiras criam universos que o público visita por anos, muitas vezes voltando aos mesmos episódios como quem reencontra velhos amigos.',
    [
      'Friends',
      'The Office',
      'Seinfeld',
      'Fleabag',
      'Brooklyn Nine-Nine',
      'Parks and Recreation',
      'Community',
      'Ted Lasso',
      'Modern Family',
      'Arrested Development',
      'Curb Your Enthusiasm',
      "It's Always Sunny in Philadelphia",
      'The Good Place',
      "Schitt's Creek",
      'Abbott Elementary',
      'What We Do in the Shadows',
      'BoJack Horseman',
      'Chaves',
      'Sai de Baixo',
      'A Grande Família',
    ],
  ),
  ranking(
    'personagens-series',
    'TV & Séries',
    'Qual personagem de série é o mais inesquecível?',
    'Alguns personagens se tornam maiores do que suas próprias séries porque reúnem atuação, escrita, contradições e uma presença que muda cada cena.',
    [
      'Walter White',
      'Tony Soprano',
      'Fleabag',
      'Eleven',
      'Tyrion Lannister',
      'Omar Little',
      'Don Draper',
      'Michael Scott',
      'Rachel Green',
      'Saul Goodman',
      'Wandinha Addams',
      'Rue Bennett',
      'Sherlock Holmes',
      'BoJack Horseman',
      'Buffy Summers',
      'Dexter Morgan',
      'Villanelle',
      'Phoebe Buffay',
      'Joel Miller',
      'Dana Scully',
    ],
  ),
  ranking(
    'livros-ler-na-vida',
    'Livros',
    'Qual livro todo mundo deveria ler uma vez na vida?',
    'Alguns livros ampliam o vocabulário, outros abrem janelas para vidas distantes e alguns simplesmente mudam a maneira como o leitor enxerga a si mesmo e o mundo.',
    [
      '1984',
      'O Sol é para Todos',
      'Cem Anos de Solidão',
      'O Pequeno Príncipe',
      'Sapiens',
      'O Diário de Anne Frank',
      'Os Irmãos Karamázov',
      'Dom Quixote',
      'Crime e Castigo',
      'Grande Sertão: Veredas',
      'Dom Casmurro',
      'A Hora da Estrela',
      'O Mundo se Despedaça',
      'Amada',
      'Frankenstein',
      'O Conto da Aia',
      'O Alquimista',
      'O Estrangeiro',
      'As Cidades Invisíveis',
      'Em Busca de Sentido',
    ],
  ),
  ranking(
    'maiores-livros-brasileiros',
    'Livros',
    'Qual é o maior livro da literatura brasileira?',
    'A literatura brasileira construiu vozes muito diferentes para falar de território, desigualdade, desejo, família, identidade e das contradições do país.',
    [
      'Grande Sertão: Veredas',
      'Dom Casmurro',
      'Memórias Póstumas de Brás Cubas',
      'Vidas Secas',
      'Macunaíma',
      'A Hora da Estrela',
      'Capitães da Areia',
      'Torto Arado',
      'Quarto de Despejo',
      'O Cortiço',
      'Sagarana',
      'O Ateneu',
      'Lavoura Arcaica',
      'Dois Irmãos',
      'A Paixão Segundo G.H.',
      'Triste Fim de Policarpo Quaresma',
      'O Quinze',
      'São Bernardo',
      'Menino de Engenho',
      "Romance d'A Pedra do Reino",
    ],
  ),
  ranking(
    'livros-infantis',
    'Livros',
    'Qual livro infantil mais marcou sua infância?',
    'Livros lidos na infância costumam permanecer ligados à voz de quem contou a história, às primeiras descobertas e ao momento em que a imaginação ganhou um mundo inteiro.',
    [
      'O Pequeno Príncipe',
      'Harry Potter e a Pedra Filosofal',
      'Alice no País das Maravilhas',
      'O Mágico de Oz',
      'Matilda',
      'A Fantástica Fábrica de Chocolate',
      'Onde Vivem os Monstros',
      'Anne de Green Gables',
      'As Crônicas de Nárnia',
      'Peter Pan',
      'Ursinho Pooh',
      'Sítio do Picapau Amarelo',
      'Meu Pé de Laranja Lima',
      'Marcelo, Marmelo, Martelo',
      'A Bolsa Amarela',
      'O Menino Maluquinho',
      'Bisa Bia, Bisa Bel',
      'Coraline',
      'A História sem Fim',
      'Momo',
    ],
  ),
  ranking(
    'personagens-literatura',
    'Livros',
    'Qual personagem da literatura é inesquecível?',
    'Personagens literários vivem primeiro na imaginação do leitor, o que permite que cada pessoa construa um rosto, uma voz e uma relação particular com eles.',
    [
      'Sherlock Holmes',
      'Elizabeth Bennet',
      'Dom Quixote',
      'Hamlet',
      'Harry Potter',
      'Frodo Bolseiro',
      'Capitu',
      'Riobaldo',
      'Anna Kariênina',
      'Holden Caulfield',
      'Jean Valjean',
      'Jane Eyre',
      'Conde Drácula',
      'A criatura de Frankenstein',
      'Hercule Poirot',
      'Alice',
      'Matilda',
      'Macabéa',
      'Edmond Dantès',
      'Atticus Finch',
    ],
  ),
  ranking(
    'adaptacoes-livros-cinema',
    'Livros',
    'Qual livro ganhou a melhor adaptação para o cinema?',
    'Adaptar um livro exige escolher o que manter, cortar ou reinventar, e os melhores filmes encontram uma linguagem própria sem perder a força do material de origem.',
    [
      'O Poderoso Chefão',
      'O Senhor dos Anéis: O Retorno do Rei',
      'Um Sonho de Liberdade',
      'O Silêncio dos Inocentes',
      'Onde os Fracos Não Têm Vez',
      'Um Estranho no Ninho',
      'Jurassic Park',
      'Clube da Luta',
      'Adoráveis Mulheres (2019)',
      'Duna: Parte Dois',
      'O Sol é para Todos',
      'A Cor Púrpura (1985)',
      'Os Bons Companheiros',
      'Garota Exemplar',
      'Blade Runner: O Caçador de Androides',
      'Filhos da Esperança',
      'Cidade de Deus',
      'As Horas',
      'Razão e Sensibilidade',
      'Los Angeles: Cidade Proibida',
    ],
  ),
  ranking(
    'livros-suspense',
    'Livros',
    'Qual é o melhor livro de suspense?',
    'Suspense depende de informação, ritmo e expectativa: o leitor sabe que algo está errado, mas continua virando as páginas para descobrir quanto ainda não percebeu.',
    [
      'E Não Sobrou Nenhum',
      'O Silêncio dos Inocentes',
      'Garota Exemplar',
      'Os Homens que Não Amavam as Mulheres',
      'O Iluminado',
      'Rebecca',
      'O Talentoso Ripley',
      'À Beira do Abismo',
      'O Nome da Rosa',
      'Antes de Dormir',
      'Objetos Cortantes',
      'A Sangue Frio',
      'O Assassinato de Roger Ackroyd',
      'Misery',
      'Sobre Meninos e Lobos',
      'O Código Da Vinci',
      'A Mulher de Branco',
      'Lugares Escuros',
      'A História Secreta',
      'Verity',
    ],
  ),
  ranking(
    'sagas-fantasia',
    'Livros',
    'Qual saga de fantasia tem o universo mais incrível?',
    'Grandes sagas criam mapas, povos, regras, mitos e conflitos que fazem o leitor sentir que existe vida muito além das páginas que conseguiu visitar.',
    [
      'O Senhor dos Anéis',
      'Harry Potter',
      'As Crônicas de Gelo e Fogo',
      'As Crônicas de Nárnia',
      'Ciclo de Terramar',
      'A Roda do Tempo',
      'Discworld',
      'Os Relatos da Guerra das Tempestades',
      'Mistborn',
      'Fronteiras do Universo',
      'The Witcher',
      'A Crônica do Matador do Rei',
      'A Torre Negra',
      'Duna',
      'Percy Jackson e os Olimpianos',
      'A Terra Partida',
      'Malazan',
      'The Sandman',
      'Dragonlance',
      'Ciclo da Herança',
    ],
  ),
  ranking(
    'escritores-brasileiros',
    'Livros',
    'Quem é o maior escritor brasileiro?',
    'Prosa, poesia, crônica, teatro e memória formam uma literatura brasileira ampla, em que cada autor encontra uma maneira diferente de reinventar a língua e o país.',
    [
      'Machado de Assis',
      'Clarice Lispector',
      'João Guimarães Rosa',
      'Graciliano Ramos',
      'Jorge Amado',
      'Carlos Drummond de Andrade',
      'Carolina Maria de Jesus',
      'Conceição Evaristo',
      'João Cabral de Melo Neto',
      'Lima Barreto',
      'Cecília Meireles',
      'Ariano Suassuna',
      'Lygia Fagundes Telles',
      'Rachel de Queiroz',
      'Mário de Andrade',
      'Raduan Nassar',
      'Milton Hatoum',
      'Hilda Hilst',
      'Rubem Fonseca',
      'Érico Veríssimo',
    ],
  ),
  ranking(
    'livros-para-reler',
    'Livros',
    'Qual livro você gostaria de esquecer para ler de novo?',
    'Certas leituras provocam uma descoberta tão forte que nasce a vontade impossível de apagar a memória e experimentar novamente cada surpresa pela primeira vez.',
    [
      'Cem Anos de Solidão',
      'Harry Potter e a Pedra Filosofal',
      'O Senhor dos Anéis',
      'Orgulho e Preconceito',
      'O Pequeno Príncipe',
      '1984',
      'O Nome do Vento',
      'Dom Casmurro',
      'A Hora da Estrela',
      'O Guia do Mochileiro das Galáxias',
      'Duna',
      'A Menina que Roubava Livros',
      'Percy Jackson e o Ladrão de Raios',
      'Belas Maldições',
      'Jane Eyre',
      'Frankenstein',
      'O Alquimista',
      'Crime e Castigo',
      'Não Me Abandone Jamais',
      'A Canção de Aquiles',
    ],
  ),
  ranking(
    'biografias-autobiografias',
    'Livros',
    'Qual é a biografia ou autobiografia mais fascinante?',
    'Uma grande história de vida combina experiência pessoal e contexto histórico, revelando as escolhas, contradições e circunstâncias por trás de uma figura real.',
    [
      'O Diário de Anne Frank',
      'Longa Caminhada até a Liberdade',
      'Minha História',
      'Steve Jobs',
      'Agassi: Autobiografia',
      'Nascido do Crime',
      'Eu Sei por que o Pássaro Canta na Gaiola',
      'A Menina da Montanha',
      'O Último Sopro de Vida',
      'Só Garotos',
      'A Autobiografia de Malcolm X',
      'Meus Experimentos com a Verdade',
      'Cisnes Selvagens',
      'Cozinha Confidencial',
      'O Castelo de Vidro',
      'Rita Lee: Uma Autobiografia',
      'Ainda Estou Aqui',
      'O Que É Isso, Companheiro?',
      'Estação Carandiru',
      'Leonardo da Vinci',
    ],
  ),
  ...[
    [
      'artistas-visuais-brasileiros',
      'Quem é o maior artista visual brasileiro?',
      'A arte brasileira reúne criadores que reinventaram pintura, escultura, instalação, fotografia e performance, levando experiências locais para conversas universais.',
      [
        'Tarsila do Amaral',
        'Candido Portinari',
        'Lygia Clark',
        'Hélio Oiticica',
        'Anita Malfatti',
        'Beatriz Milhazes',
        'Vik Muniz',
        'Adriana Varejão',
        'Lygia Pape',
        'Di Cavalcanti',
        'Arthur Bispo do Rosário',
        'Aleijadinho',
        'Amilcar de Castro',
        'Maria Martins',
        'Lasar Segall',
        'Tomie Ohtake',
        'Rosana Paulino',
        'Ernesto Neto',
        'Cildo Meireles',
        'Alfredo Volpi',
      ],
    ],
    [
      'obras-arte-historia',
      'Qual é a maior obra de arte da história?',
      'Algumas obras atravessam séculos porque combinam domínio técnico, força simbólica e uma imagem capaz de permanecer reconhecível mesmo fora dos museus.',
      [
        'Mona Lisa',
        'A Noite Estrelada',
        'Guernica',
        'Teto da Capela Sistina',
        'A Última Ceia',
        'O Nascimento de Vênus',
        'A Ronda Noturna',
        'Moça com Brinco de Pérola',
        'O Grito',
        'A Persistência da Memória',
        'As Meninas',
        'A Liberdade Guiando o Povo',
        'O Beijo, de Gustav Klimt',
        'O Jardim das Delícias Terrenas',
        'Nighthawks',
        'American Gothic',
        'A Grande Onda de Kanagawa',
        'Abaporu',
        'Davi, de Michelangelo',
        'Vênus de Milo',
      ],
    ],
    [
      'esculturas-historia',
      'Qual é a escultura mais impressionante da história?',
      'Da pedra antiga às instalações contemporâneas, esculturas transformam matéria, escala e espaço em experiências que mudam conforme o visitante se movimenta.',
      [
        'Davi, de Michelangelo',
        'Pietà',
        'O Pensador',
        'Vênus de Milo',
        'Vitória de Samotrácia',
        'Exército de Terracota',
        'Discóbolo',
        'Êxtase de Santa Teresa',
        'O Beijo, de Rodin',
        'Moais da Ilha de Páscoa',
        'Estátua da Liberdade',
        'Cristo Redentor',
        'Cloud Gate',
        'Maman',
        'Balloon Dog',
        'Os Burgueses de Calais',
        'Pássaro no Espaço',
        'Formas Únicas da Continuidade no Espaço',
        'Gálata Moribundo',
        'Laocoonte e Seus Filhos',
      ],
    ],
    [
      'museus-mundo',
      'Qual museu você mais gostaria de visitar?',
      'Museus podem guardar coleções enciclopédicas, revelar uma cultura específica ou fazer da própria arquitetura parte decisiva da visita.',
      [
        'Museu do Louvre',
        'Museu do Prado',
        'Metropolitan Museum of Art',
        'Museu Britânico',
        'Museus do Vaticano',
        'Galeria Uffizi',
        'MoMA',
        'Rijksmuseum',
        'Museu Hermitage',
        'Centro Pompidou',
        'Museu de Orsay',
        'Tate Modern',
        'Guggenheim Bilbao',
        'National Gallery de Londres',
        'Museu de Pérgamo',
        'Museu da Acrópole',
        'Inhotim',
        'MASP',
        'Museu Nacional de Antropologia do México',
        'Art Institute of Chicago',
      ],
    ],
    [
      'movimentos-artisticos',
      'Qual movimento artístico mais mudou a história?',
      'Movimentos artísticos nascem de rupturas, diálogos e manifestos, propondo novas maneiras de representar o mundo e de pensar o papel do artista.',
      [
        'Renascimento',
        'Impressionismo',
        'Expressionismo',
        'Cubismo',
        'Surrealismo',
        'Barroco',
        'Modernismo',
        'Pop Art',
        'Expressionismo Abstrato',
        'Dadaísmo',
        'Bauhaus',
        'Romantismo',
        'Realismo',
        'Futurismo',
        'Construtivismo',
        'Minimalismo',
        'Arte Conceitual',
        'Neoclassicismo',
        'Art Nouveau',
        'Arte de Rua e Grafite',
      ],
    ],
    [
      'fotografos-historia',
      'Quem é o maior fotógrafo da história?',
      'Grandes fotógrafos unem olhar, técnica e oportunidade para transformar um instante real em documento, pergunta ou imagem inesquecível.',
      [
        'Henri Cartier-Bresson',
        'Ansel Adams',
        'Dorothea Lange',
        'Robert Capa',
        'Sebastião Salgado',
        'Vivian Maier',
        'Diane Arbus',
        'Gordon Parks',
        'Steve McCurry',
        'Annie Leibovitz',
        'Richard Avedon',
        'Irving Penn',
        'Cindy Sherman',
        'Robert Frank',
        'Nan Goldin',
        'Man Ray',
        'Helmut Newton',
        'William Eggleston',
        'Daido Moriyama',
        'Claudia Andujar',
      ],
    ],
    [
      'fotografias-iconicas',
      'Qual é a fotografia mais icônica da história?',
      'Uma fotografia icônica pode condensar um acontecimento, criar um símbolo universal ou mudar para sempre a maneira como uma época é lembrada.',
      [
        'Mãe Migrante',
        'Menina Afegã',
        'O Homem do Tanque',
        'O Beijo da Times Square',
        'Almoço no Topo de um Arranha-céu',
        'Earthrise',
        'The Blue Marble',
        'Bandeira em Iwo Jima',
        'Guerrillero Heroico',
        'A Menina do Napalm',
        'Einstein Mostrando a Língua',
        'Muhammad Ali sobre Sonny Liston',
        'Marilyn Monroe no Metrô',
        'Dalí Atomicus',
        'O Beijo do Hôtel de Ville',
        'Serra Pelada, de Sebastião Salgado',
        'Os Beatles na Abbey Road',
        'O Homem na Lua',
        'O Desastre do Hindenburg',
        'O Menino do Gueto de Varsóvia',
      ],
    ],
    [
      'artistas-rua',
      'Quem é o maior artista de rua?',
      'A arte urbana ocupa muros, trens e fachadas para dialogar diretamente com a cidade, misturando identidade visual, comentário social e efemeridade.',
      [
        'Banksy',
        'Jean-Michel Basquiat',
        'Keith Haring',
        'Os Gêmeos',
        'Eduardo Kobra',
        'Shepard Fairey',
        'JR',
        'Invader',
        'Blu',
        'Vhils',
        'Lady Pink',
        'Swoon',
        'Futura 2000',
        'Rammellzee',
        'Blek le Rat',
        'Faith47',
        'Bordalo II',
        'Nunca',
        'Nina Pandolfo',
        'Zezão',
      ],
    ],
    [
      'obras-arte-em-casa',
      'Qual obra de arte você teria em casa?',
      'Escolher uma obra para conviver todos os dias envolve beleza, personalidade, atmosfera e a relação particular que cada imagem cria com quem a observa.',
      [
        'A Noite Estrelada',
        'A Grande Onda de Kanagawa',
        'O Beijo, de Gustav Klimt',
        'Nenúfares',
        'O Nascimento de Vênus',
        'Composição VIII',
        'A Dança, de Matisse',
        'Nighthawks',
        'Abaporu',
        'Girassóis',
        'Moça com Brinco de Pérola',
        'Latas de Sopa Campbell',
        'O Filho do Homem',
        'American Gothic',
        'As Duas Fridas',
        'O Jardim das Delícias Terrenas',
        'O Grito',
        'Terraço do Café à Noite',
        'Primavera, de Botticelli',
        'A Persistência da Memória',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Arte', question, focus, options)),
  ...[
    [
      'pecas-atemporais',
      'Qual é a peça de roupa mais atemporal?',
      'Peças atemporais sobrevivem às mudanças de tendência porque combinam versatilidade, identidade clara e facilidade para criar novas composições.',
      [
        'Calça jeans',
        'Camisa branca',
        'Vestido preto',
        'Blazer',
        'Jaqueta de couro',
        'Trench coat',
        'Tênis branco',
        'Camiseta básica',
        'Calça de alfaiataria',
        'Jaqueta jeans',
        'Bota preta',
        'Mocassim',
        'Suéter de tricô',
        'Saia midi',
        'Lenço',
        'Terno',
        'Cardigan',
        'Camisa polo',
        'Tênis Converse All Star',
        'Óculos aviador',
      ],
    ],
    [
      'epocas-moda',
      'Qual época teve a moda mais bonita?',
      'Cada período traduziu valores, tecnologia e comportamento em silhuetas próprias, fazendo da roupa um retrato imediato de seu tempo.',
      [
        'Egito Antigo',
        'Grécia e Roma Antigas',
        'Idade Média',
        'Renascimento',
        'Barroco',
        'Rococó',
        'Período Regencial',
        'Era Vitoriana',
        'Belle Époque',
        'Anos 1920',
        'Anos 1930',
        'Anos 1940',
        'Anos 1950',
        'Anos 1960',
        'Anos 1970',
        'Anos 1980',
        'Anos 1990',
        'Anos 2000',
        'Anos 2010',
        'Anos 2020',
      ],
    ],
    [
      'icones-estilo',
      'Quem é o maior ícone de estilo?',
      'Ícones de estilo não apenas vestem tendências: eles criam uma linguagem própria, mudam referências e fazem cada aparição parecer uma declaração.',
      [
        'Audrey Hepburn',
        'David Bowie',
        'Grace Jones',
        'Princesa Diana',
        'Rihanna',
        'Zendaya',
        'Harry Styles',
        'Madonna',
        'Jane Birkin',
        'Pharrell Williams',
        'Iman',
        'Kate Moss',
        'Jackie Kennedy',
        'Marlene Dietrich',
        'Cher',
        'Naomi Campbell',
        'Timothée Chalamet',
        'Tilda Swinton',
        'Beyoncé',
        'Bad Bunny',
      ],
    ],
    [
      'estilistas-historia',
      'Quem é o maior estilista da história?',
      'Grandes estilistas reinventaram volumes, materiais, códigos sociais e a própria ideia de luxo, deixando assinaturas que continuam reconhecíveis.',
      [
        'Coco Chanel',
        'Yves Saint Laurent',
        'Alexander McQueen',
        'Vivienne Westwood',
        'Giorgio Armani',
        'Miuccia Prada',
        'Rei Kawakubo',
        'Karl Lagerfeld',
        'Christian Dior',
        'Gianni Versace',
        'Cristóbal Balenciaga',
        'Elsa Schiaparelli',
        'Tom Ford',
        'Marc Jacobs',
        'Virgil Abloh',
        'Issey Miyake',
        'Yohji Yamamoto',
        'Valentino Garavani',
        'Pierre Cardin',
        'Zuzu Angel',
      ],
    ],
    [
      'acessorios-look',
      'Qual acessório mais transforma um look?',
      'Um acessório pode equilibrar proporções, introduzir cor e textura ou mudar completamente o tom de uma roupa com um único detalhe.',
      [
        'Óculos de sol',
        'Relógio',
        'Lenço',
        'Chapéu',
        'Bolsa',
        'Brincos',
        'Colar',
        'Pulseira',
        'Cinto',
        'Anel',
        'Boné',
        'Gravata',
        'Broche',
        'Luvas',
        'Suspensório',
        'Bandana',
        'Acessório de cabelo',
        'Meias',
        'Lenço de bolso',
        'Mochila',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Moda', question, focus, options)),
  ...[
    [
      'humoristas-brasileiros',
      'Quem é o maior humorista brasileiro?',
      'O humor brasileiro passou por rádio, circo, cinema, televisão, teatro, stand-up e internet, revelando artistas capazes de traduzir épocas inteiras em personagens e frases.',
      [
        'Chico Anysio',
        'Jô Soares',
        'Paulo Gustavo',
        'Mussum',
        'Renato Aragão',
        'Tom Cavalcante',
        'Dercy Gonçalves',
        'Tatá Werneck',
        'Marcelo Adnet',
        'Fábio Porchat',
        'Gregório Duvivier',
        'Dani Calabresa',
        'Whindersson Nunes',
        'Tiririca',
        'Costinha',
        'Oscarito',
        'Grande Otelo',
        'Nair Bello',
        'Marco Luque',
        'Leandro Hassum',
      ],
    ],
    [
      'icones-pop-brasileiros',
      'Quem é o maior ícone pop brasileiro?',
      'Ícones pop ultrapassam sua área de origem e passam a representar o Brasil por meio de imagens, conquistas, gestos e histórias reconhecidas por várias gerações.',
      [
        'Carmen Miranda',
        'Pelé',
        'Ayrton Senna',
        'Xuxa',
        'Gisele Bündchen',
        'Fernanda Montenegro',
        'Roberto Carlos',
        'Hebe Camargo',
        'Neymar',
        'Ivete Sangalo',
        'Anitta',
        'Gilberto Gil',
        'Caetano Veloso',
        'Gal Costa',
        'Rita Lee',
        'Silvio Santos',
        'Elza Soares',
        'Marília Mendonça',
        'Wagner Moura',
        'Sônia Braga',
      ],
    ],
    [
      'celebridades-estilosas',
      'Qual celebridade tem o melhor estilo?',
      'Algumas celebridades tratam tapetes vermelhos, turnês e aparições públicas como extensões de seu trabalho, criando momentos de moda que viram referência.',
      [
        'Rihanna',
        'Zendaya',
        'Lady Gaga',
        'David Beckham',
        'Timothée Chalamet',
        'Harry Styles',
        'Beyoncé',
        'Bad Bunny',
        'Tilda Swinton',
        'Pharrell Williams',
        'Janelle Monáe',
        'A$AP Rocky',
        'Anitta',
        'Iza',
        'Sabrina Sato',
        'Marina Ruy Barbosa',
        'Lewis Hamilton',
        'Cate Blanchett',
        'Pedro Pascal',
        'Lupita Nyong’o',
      ],
    ],
    [
      'famosos-melhor-amigo',
      'Qual famoso parece que seria seu melhor amigo?',
      'Carisma público, senso de humor e espontaneidade fazem algumas personalidades parecerem próximas, mesmo quando essa impressão vem apenas de entrevistas e trabalhos.',
      [
        'Keanu Reeves',
        'Jennifer Lawrence',
        'Ryan Reynolds',
        'Emma Stone',
        'Pedro Pascal',
        'Fernanda Torres',
        'Selton Mello',
        'Taís Araújo',
        'Lázaro Ramos',
        'Ivete Sangalo',
        'Paulo Vieira',
        'Tatá Werneck',
        'Fábio Porchat',
        'Gil do Vigor',
        'Sandy',
        'Rodrigo Santoro',
        'Jack Black',
        'Viola Davis',
        'Tom Hanks',
        'Drew Barrymore',
      ],
    ],
    [
      'apresentadores-tv-brasil',
      'Quem é o maior apresentador da TV brasileira?',
      'Apresentadores transformam formatos em encontros, conduzindo auditórios, entrevistas, variedades e competições com uma presença que muitas vezes define o próprio programa.',
      [
        'Silvio Santos',
        'Hebe Camargo',
        'Chacrinha',
        'Jô Soares',
        'Xuxa',
        'Faustão',
        'Gugu Liberato',
        'Eliana',
        'Luciano Huck',
        'Ana Maria Braga',
        'Sabrina Sato',
        'Marcos Mion',
        'Tatá Werneck',
        'Serginho Groisman',
        'Pedro Bial',
        'Angélica',
        'Fátima Bernardes',
        'Cazé Peçanha',
        'Palmirinha Onofre',
        'Raul Gil',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Famosos', question, focus, options)),
  ...[
    [
      'fenomenos-natureza',
      'Qual é o fenômeno da natureza mais impressionante?',
      'Fenômenos naturais revelam forças, escalas e condições raras do planeta, produzindo paisagens que podem ser belas, extremas ou transformadoras.',
      [
        'Aurora boreal',
        'Eclipse solar total',
        'Erupção vulcânica',
        'Bioluminescência no mar',
        'Tempestade elétrica',
        'Tornado',
        'Furacão',
        'Tsunami',
        'Gêiser',
        'Arco-íris',
        'Eclipse lunar',
        'Chuva de meteoros',
        'Supercélula',
        'Halo solar',
        'Mar de nuvens',
        'Arco circum-horizontal',
        'Caverna de gelo',
        'Deserto florido',
        'Rolos de neve',
        'Nuvens lenticulares',
      ],
    ],
    [
      'animais-extintos',
      'Qual animal extinto você mais gostaria de ver vivo?',
      'Espécies extintas ajudam a imaginar ecossistemas desaparecidos e mostram como clima, evolução e ação humana alteram profundamente a vida no planeta.',
      [
        'Tiranossauro rex',
        'Mamute-lanoso',
        'Dodô',
        'Tigre-dentes-de-sabre',
        'Megalodonte',
        'Tricerátopo',
        'Preguiça-gigante',
        'Tilacino',
        'Quaga',
        'Pombo-passageiro',
        'Moa',
        'Auroque',
        'Alce-gigante',
        'Archaeopteryx',
        'Dunkleosteus',
        'Espinossauro',
        'Rinoceronte-lanoso',
        'Gliptodonte',
        'Ara-gigante',
        'Lobo-terrível',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Natureza', question, focus, options)),
  ...[
    [
      'carros-brasileiros-iconicos',
      'Qual é o carro mais icônico do Brasil?',
      'Carros populares, esportivos nacionais e sedãs de prestígio ajudaram a contar a história das ruas brasileiras e ainda despertam lembranças muito diferentes.',
      [
        'Volkswagen Fusca',
        'Volkswagen Kombi',
        'Chevrolet Opala',
        'Chevrolet Chevette',
        'Volkswagen Gol',
        'Fiat Uno Mille',
        'Chevrolet Monza',
        'Volkswagen Brasília',
        'Ford Maverick',
        'Ford Corcel',
        'Fiat 147',
        'Ford Escort XR3',
        'Volkswagen Santana',
        'Chevrolet Kadett GSi',
        'Fiat Tempra Turbo',
        'Chevrolet Omega',
        'Fiat Palio',
        'Chevrolet Celta',
        'Volkswagen Saveiro',
        'Puma GTB',
      ],
    ],
    [
      'carros-esportivos',
      'Qual é o maior carro esportivo da história?',
      'Os esportivos mais celebrados combinam desempenho, engenharia, desenho e personalidade, muitas vezes se tornando símbolos definitivos de suas décadas.',
      [
        'Ferrari F40',
        'Porsche 911',
        'Lamborghini Miura',
        'McLaren F1',
        'Mercedes-Benz 300 SL',
        'Ford GT40',
        'Nissan Skyline GT-R R34',
        'Toyota Supra Mk4',
        'Chevrolet Corvette Stingray',
        'Audi R8',
        'Honda NSX',
        'BMW M3 E30',
        'Jaguar E-Type',
        'Shelby Cobra',
        'Bugatti Veyron',
        'Lancia Stratos',
        'Dodge Viper',
        'Aston Martin DB5',
        'Lotus Esprit',
        'Mazda RX-7',
      ],
    ],
    [
      'motos-iconicas',
      'Qual é a moto mais icônica da história?',
      'Algumas motocicletas definiram categorias inteiras, popularizaram novas tecnologias ou conquistaram uma silhueta imediatamente reconhecível.',
      [
        'Harley-Davidson Sportster',
        'Honda CB 750',
        'Ducati 916',
        'Triumph Bonneville',
        'Yamaha RD 350',
        'Honda CG 125',
        'Vespa PX',
        'BMW R 1250 GS',
        'Kawasaki Ninja H2',
        'Suzuki Hayabusa',
        'Yamaha XT 600',
        'Honda Super Cub',
        'Indian Chief',
        'Ducati Monster',
        'Royal Enfield Bullet',
        'Kawasaki Z1',
        'Honda Gold Wing',
        'Yamaha YZF-R1',
        'KTM 990 Adventure',
        'MV Agusta F4',
      ],
    ],
    [
      'marcas-carros',
      'Qual é a maior marca de carros da história?',
      'Uma grande marca automotiva pode se destacar por inovação, competição, luxo, confiabilidade ou pela capacidade de colocar milhões de pessoas em movimento.',
      [
        'Ferrari',
        'Porsche',
        'Mercedes-Benz',
        'BMW',
        'Toyota',
        'Volkswagen',
        'Honda',
        'Ford',
        'Lamborghini',
        'Audi',
        'Volvo',
        'Jaguar',
        'Aston Martin',
        'Chevrolet',
        'Nissan',
        'Subaru',
        'Alfa Romeo',
        'Bugatti',
        'Rolls-Royce',
        'Tesla',
      ],
    ],
    [
      'carros-cinema-tv',
      'Qual é o carro mais inesquecível do cinema e da TV?',
      'Em grandes histórias, um veículo pode ganhar voz, personalidade e função dramática até se tornar tão famoso quanto os personagens que transporta.',
      [
        'DeLorean de De Volta para o Futuro',
        'Batmóvel',
        'Aston Martin DB5 de James Bond',
        'Ecto-1 de Os Caça-Fantasmas',
        'Mach 5 de Speed Racer',
        'KITT de A Supermáquina',
        'Herbie',
        'Dodge Charger de Velozes e Furiosos',
        'Ford Mustang de Bullitt',
        'Mini Cooper de Uma Saída de Mestre',
        'Interceptor de Mad Max',
        'General Lee de Os Gatões',
        'Máquina de Mistério de Scooby-Doo',
        'Relâmpago McQueen',
        'Toyota Supra de Velozes e Furiosos',
        'Bumblebee',
        'Bluesmobile de Os Irmãos Cara de Pau',
        'Ford Anglia de Harry Potter',
        'Lotus Esprit de 007',
        'Gran Torino de Starsky & Hutch',
      ],
    ],
    [
      'carros-design',
      'Qual carro tem o design mais bonito da história?',
      'O desenho automotivo equilibra aerodinâmica, proporção, identidade e emoção, produzindo formas que podem continuar modernas décadas depois do lançamento.',
      [
        'Jaguar E-Type',
        'Citroën DS',
        'Porsche 911',
        'Lamborghini Miura',
        'Mercedes-Benz 300 SL',
        'Ferrari 250 GTO',
        'Alfa Romeo 33 Stradale',
        'Bugatti Type 57SC Atlantic',
        'Aston Martin DB5',
        'Volkswagen Fusca',
        'Mini Cooper',
        'Chevrolet Corvette Stingray 1963',
        'Ford GT40',
        'Lancia Stratos',
        'BMW 507',
        'Toyota 2000GT',
        'Honda NSX',
        'Mazda RX-7 FD',
        'Alpine A110',
        'Audi Quattro',
      ],
    ],
    [
      'carros-viagem-estrada',
      'Qual carro você escolheria para uma grande viagem?',
      'O carro ideal de viagem pode privilegiar conforto, espaço, robustez, prazer ao volante ou simplesmente a sensação de liberdade que combina com a estrada.',
      [
        'Land Rover Defender',
        'Toyota Land Cruiser',
        'Volvo XC90',
        'Porsche 911',
        'Subaru Outback',
        'Ford Mustang',
        'Jeep Wrangler',
        'Volkswagen Kombi',
        'Mercedes-Benz Classe G',
        'Honda CR-V',
        'Toyota RAV4',
        'Chevrolet Suburban',
        'BMW Série 5 Touring',
        'Audi RS6 Avant',
        'Mazda MX-5',
        'Volvo 240 Wagon',
        'Ford Bronco',
        'Citroën DS',
        'Lexus GX',
        'Volkswagen Golf',
      ],
    ],
    [
      'carros-eletricos',
      'Qual é o melhor carro elétrico já lançado?',
      'Os elétricos recentes disputam autonomia, eficiência, desempenho, preço e experiência digital enquanto ajudam a redesenhar toda a indústria automotiva.',
      [
        'Tesla Model S',
        'Porsche Taycan',
        'Hyundai Ioniq 5',
        'Kia EV6',
        'Lucid Air',
        'Rivian R1T',
        'BMW i4',
        'Mercedes-Benz EQS',
        'Ford Mustang Mach-E',
        'Volkswagen ID. Buzz',
        'Audi e-tron GT',
        'Renault Zoe',
        'Nissan Leaf',
        'Chevrolet Bolt EV',
        'BYD Seal',
        'Volvo EX30',
        'Polestar 2',
        'Jaguar I-Pace',
        'Rimac Nevera',
        'Fiat 500e',
      ],
    ],
    [
      'corridas-automobilismo',
      'Qual é a maior corrida do automobilismo?',
      'As provas mais lendárias testam velocidade, resistência, estratégia e coragem em circuitos e terrenos que criaram tradições próprias.',
      [
        '24 Horas de Le Mans',
        'Grande Prêmio de Mônaco',
        '500 Milhas de Indianápolis',
        'Rali Dakar',
        '24 Horas de Nürburgring',
        'Daytona 500',
        'Bathurst 1000',
        'TT da Ilha de Man',
        'Rali de Monte Carlo',
        'Mille Miglia',
        'Subida Internacional de Pikes Peak',
        '12 Horas de Sebring',
        'Targa Florio',
        'Carrera Panamericana',
        'Grande Prêmio de São Paulo',
        'Rali da Finlândia',
        'Baja 1000',
        '24 Horas de Spa',
        'Grande Prêmio de Macau',
        'Rali Safari',
      ],
    ],
    [
      'pilotos-automobilismo',
      'Quem é o maior piloto do automobilismo?',
      'Comparar pilotos de categorias e épocas diferentes envolve velocidade pura, títulos, versatilidade, rivalidades e a marca emocional deixada nos fãs.',
      [
        'Ayrton Senna',
        'Michael Schumacher',
        'Lewis Hamilton',
        'Juan Manuel Fangio',
        'Alain Prost',
        'Jim Clark',
        'Niki Lauda',
        'Max Verstappen',
        'Jackie Stewart',
        'Fernando Alonso',
        'Sebastian Vettel',
        'Stirling Moss',
        'Nelson Piquet',
        'Emerson Fittipaldi',
        'Mario Andretti',
        'A. J. Foyt',
        'Tom Kristensen',
        'Sébastien Loeb',
        'Dale Earnhardt',
        'Valentino Rossi',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Motores', question, focus, options)),
  ...[
    [
      'jogos-mundo-aberto',
      'Qual é o melhor jogo de mundo aberto?',
      'Os melhores mundos abertos equilibram liberdade, descoberta, regras coerentes e histórias capazes de surgir tanto do roteiro quanto das escolhas do jogador.',
      [
        'Red Dead Redemption 2',
        'The Legend of Zelda: Breath of the Wild',
        'Grand Theft Auto V',
        'Elden Ring',
        'The Witcher 3: Wild Hunt',
        'The Elder Scrolls V: Skyrim',
        'Minecraft',
        'Ghost of Tsushima',
        'Cyberpunk 2077',
        'Horizon Zero Dawn',
        'Fallout: New Vegas',
        'Metal Gear Solid V: The Phantom Pain',
        'Assassin’s Creed IV: Black Flag',
        'Grand Theft Auto: San Andreas',
        'Far Cry 3',
        'Marvel’s Spider-Man',
        'Death Stranding',
        'No Man’s Sky',
        'Subnautica',
        'The Legend of Zelda: Tears of the Kingdom',
      ],
    ],
    [
      'personagens-videogame',
      'Qual é o maior personagem dos videogames?',
      'Personagens de videogame se tornam ícones pela combinação de visual, habilidades, personalidade e pelas experiências que o jogador vive ao controlá-los.',
      [
        'Mario',
        'Link',
        'Lara Croft',
        'Sonic',
        'Kratos',
        'Master Chief',
        'Pikachu',
        'Pac-Man',
        'Samus Aran',
        'Solid Snake',
        'Cloud Strife',
        'Geralt de Rívia',
        'Ellie',
        'Nathan Drake',
        'Mega Man',
        'Chun-Li',
        'Ryu',
        'Crash Bandicoot',
        'Donkey Kong',
        'Kirby',
      ],
    ],
    [
      'trilhas-jogos',
      'Qual jogo tem a melhor trilha sonora?',
      'Uma grande trilha pode orientar o ritmo da ação, construir mundos inteiros e permanecer na memória mesmo quando o controle já foi deixado de lado.',
      [
        'The Last of Us',
        'The Legend of Zelda: Ocarina of Time',
        'Final Fantasy VII',
        'The Elder Scrolls V: Skyrim',
        'Halo',
        'Super Mario Galaxy',
        'Chrono Trigger',
        'NieR: Automata',
        'Journey',
        'Donkey Kong Country 2',
        'Hollow Knight',
        'Undertale',
        'Doom',
        'Persona 5',
        'Castlevania: Symphony of the Night',
        'Red Dead Redemption 2',
        'Minecraft',
        'Street Fighter II',
        'Sonic the Hedgehog 2',
        'Shadow of the Colossus',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Jogos', question, focus, options)),
  ...[
    [
      'invencoes-tecnologicas',
      'Qual invenção tecnológica mais mudou o mundo?',
      'As invenções mais transformadoras ampliam capacidades humanas, criam novas infraestruturas e alteram hábitos que antes pareciam permanentes.',
      [
        'Internet',
        'Transistor',
        'Telefone',
        'Lâmpada elétrica',
        'Imprensa de tipos móveis',
        'Computador',
        'Smartphone',
        'GPS',
        'Avião',
        'Rádio',
        'Televisão',
        'Câmera fotográfica',
        'Máquina a vapor',
        'Microprocessador',
        'Bateria recarregável',
        'Refrigeração artificial',
        'Laser',
        'Satélite artificial',
        'Impressora 3D',
        'Wi-Fi',
      ],
    ],
    [
      'gadgets-anos-2000',
      'Qual gadget mais marcou os anos 2000?',
      'A primeira década dos anos 2000 misturou celulares com personalidade, música digital, câmeras compactas e aparelhos que anteciparam a vida permanentemente conectada.',
      [
        'iPod',
        'Nokia 3310',
        'BlackBerry',
        'Motorola Razr V3',
        'PlayStation 2',
        'Nintendo Wii',
        'PSP',
        'Primeiro iPhone',
        'Câmera digital compacta',
        'PalmPilot',
        'iMac G3',
        'Pen drive',
        'DVD portátil',
        'TiVo',
        'GPS automotivo Garmin',
        'Webcam',
        'MP3 player',
        'Xbox 360',
        'Nintendo DS',
        'Netbook',
      ],
    ],
    [
      'tecnologias-ficcao',
      'Qual tecnologia da ficção você mais gostaria que existisse?',
      'A ficção imagina ferramentas impossíveis para explorar desejos muito reais: viajar, curar, compreender, criar e ultrapassar limites físicos.',
      [
        'Teletransporte',
        'Holodeck',
        'Sabre de luz',
        'Carro voador',
        'Máquina do tempo',
        'Tradutor universal',
        'Replicador de matéria',
        'Capa de invisibilidade',
        'Hoverboard',
        'Interface neural perfeita',
        'Androide assistente',
        'Fusão nuclear limpa e ilimitada',
        'Sono criogênico seguro',
        'Gravidade artificial',
        'Comunicador quântico instantâneo',
        'Scanner médico instantâneo',
        'Jetpack seguro',
        'Materiais autorreparáveis',
        'Elevador espacial',
        'Habitat autossuficiente em Marte',
      ],
    ],
    [
      'celulares-historia',
      'Qual celular mais mudou a história?',
      'Alguns celulares popularizaram formatos, recursos e comportamentos que redesenharam a comunicação muito antes de desaparecerem dos bolsos.',
      [
        'Motorola DynaTAC 8000X',
        'Nokia 3310',
        'BlackBerry Bold',
        'Motorola Razr V3',
        'Primeiro iPhone',
        'Samsung Galaxy S',
        'Nokia N95',
        'T-Mobile Sidekick',
        'Palm Treo 600',
        'iPhone 4',
        'Samsung Galaxy Note',
        'Moto G',
        'Xiaomi Mi 1',
        'Google Pixel',
        'OnePlus One',
        'Nokia Lumia 920',
        'HTC Dream',
        'Motorola StarTAC',
        'Sony Ericsson W800',
        'LG Chocolate',
      ],
    ],
    [
      'redes-sociais-impactantes',
      'Qual rede social mais mudou a internet?',
      'Redes e plataformas sociais criaram novas formas de amizade, trabalho, entretenimento e debate público, cada uma com sua linguagem própria.',
      [
        'Orkut',
        'Facebook',
        'Instagram',
        'YouTube',
        'Twitter / X',
        'TikTok',
        'WhatsApp',
        'Reddit',
        'LinkedIn',
        'Snapchat',
        'Pinterest',
        'Tumblr',
        'MySpace',
        'MSN Messenger',
        'Telegram',
        'Discord',
        'Twitch',
        'Vine',
        'Threads',
        'ICQ',
      ],
    ],
    [
      'marcas-tecnologia',
      'Qual é a maior marca de tecnologia da história?',
      'Marcas de tecnologia podem ser lembradas por produtos, plataformas, pesquisa ou pela capacidade de transformar uma inovação em parte da vida cotidiana.',
      [
        'Apple',
        'Microsoft',
        'Google',
        'Samsung',
        'Sony',
        'IBM',
        'Intel',
        'Nvidia',
        'Amazon',
        'Meta',
        'Nintendo',
        'Tesla',
        'Xiaomi',
        'Huawei',
        'Dell',
        'HP',
        'Adobe',
        'Oracle',
        'Spotify',
        'OpenAI',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Tecnologia', question, focus, options)),
  ...[
    [
      'embalagens-iconicas',
      'Qual é a embalagem mais icônica da história?',
      'Uma embalagem marcante protege o produto e ao mesmo tempo cria uma forma, cor ou ritual tão forte que pode ser reconhecida sem o nome da marca.',
      [
        'Garrafa de vidro da Coca-Cola',
        'Lata de sopa Campbell’s',
        'Caixa azul da Tiffany & Co.',
        'Caixa triangular do Toblerone',
        'Tubo de Pringles',
        'Garrafa de ketchup Heinz',
        'Caixa branca do iPhone',
        'Garrafa de Absolut Vodka',
        'Frasco de Chanel Nº 5',
        'Embalagem de KitKat',
        'Caixa do McLanche Feliz',
        'Lata de Leite Moça',
        'Lata de Nescau',
        'Caixa amarela de Maizena',
        'Lata de Bombril',
        'Pote de Nutella',
        'Garrafa de Perrier',
        'Caixa de lápis Faber-Castell',
        'Pote de Aveia Quaker',
        'Garrafa de molho Tabasco',
      ],
    ],
    [
      'objetos-design',
      'Qual objeto cotidiano tem o melhor design?',
      'O grande design torna um objeto simples de usar, agradável de ver e tão coerente que sua forma parece inevitável mesmo depois de muitas décadas.',
      [
        'Caneta BIC Cristal',
        'Isqueiro Zippo',
        'Canivete suíço',
        'Câmera Polaroid',
        'Lambreta Vespa',
        'Poltrona Eames Lounge',
        'Luminária Anglepoise',
        'Batedeira KitchenAid',
        'Chaleira Alessi 9093',
        'Calculadora Braun ET66',
        'iPod',
        'Peça de LEGO',
        'Garrafa de Coca-Cola',
        'Cafeteira Moka Express',
        'Cubo Mágico',
        'Bloco Post-it',
        'Máquina de escrever Olivetti Valentine',
        'Garrafa térmica',
        'Caneta Parker 51',
        'Relógio Casio G-Shock',
      ],
    ],
    [
      'produtos-brasileiros-iconicos',
      'Qual produto mais marcou gerações de brasileiros?',
      'Alguns produtos entram na memória coletiva por sua presença constante em casas, escolas, praias, mesas e propagandas de diferentes épocas.',
      [
        'Havaianas',
        'Bombril',
        'Leite Moça',
        'Nescau',
        'Guaraná Antarctica',
        'Paçoquita',
        'Bis',
        'Natura Ekos',
        'Melissa',
        'Malbec de O Boticário',
        'Talheres Tramontina',
        'Filtro de barro São João',
        'Meu Primeiro Gradiente',
        'Cachaça 51',
        'Fandangos',
        'Sandálias Rider',
        'Serenata de Amor',
        'Panettone Bauducco',
        'Leite de Rosas',
        'Pomada Minancora',
      ],
    ],
  ].map(([id, question, focus, options]) => ranking(id, 'Produtos', question, focus, options)),
];

const factsByCategory = Object.freeze({
  Cinema: [
    'Gêneros cinematográficos mudam com o tempo e frequentemente se misturam dentro do mesmo filme.',
    'Prêmios, bilheteria, influência cultural e gosto do público medem aspectos diferentes de uma obra.',
  ],
  'TV & Séries': [
    'Séries e novelas podem ser avaliadas por roteiro, atuação, personagens, impacto cultural e capacidade de permanecer na memória.',
    'A forma de assistir televisão mudou com reprises, canais por assinatura e plataformas de streaming.',
  ],
  Livros: [
    'Traduções e edições diferentes podem alterar a experiência de leitura de uma mesma obra.',
    'Importância histórica, qualidade literária e prazer de leitura são critérios distintos.',
  ],
  Arte: [
    'Movimentos, técnicas e contextos históricos influenciam a maneira como uma obra é percebida.',
    'Valor de mercado, fama e relevância artística não significam necessariamente a mesma coisa.',
  ],
  Moda: [
    'Tendências costumam reaparecer reinterpretadas por novas gerações.',
    'Moda pode combinar função, identidade, comportamento, técnica e memória cultural.',
  ],
  Famosos: [
    'A imagem pública é construída por trabalhos, entrevistas, aparições e redes sociais.',
    'Popularidade e talento são percepções subjetivas e mudam entre gerações.',
  ],
  Natureza: [
    'Fenômenos naturais e espécies extintas ajudam a compreender a longa história do planeta.',
    'Descobertas científicas podem revisar estimativas sobre aparência, comportamento e origem.',
  ],
  Motores: [
    'Design, desempenho, confiabilidade e memória afetiva são critérios diferentes para avaliar um veículo.',
    'Modelos marcantes costumam refletir a tecnologia, a cultura e as necessidades de sua época.',
  ],
  Jogos: [
    'Jogabilidade, narrativa, personagens e inovação podem pesar de formas diferentes na escolha.',
    'Franquias de videogame frequentemente atravessam gerações de consoles e ganham novas interpretações.',
  ],
  Tecnologia: [
    'Tecnologias podem transformar hábitos antes mesmo de se tornarem acessíveis para todas as pessoas.',
    'Impacto social, utilidade cotidiana e inovação técnica são critérios independentes.',
  ],
  Produtos: [
    'Design, utilidade, lembrança afetiva e força de marca influenciam a percepção de um produto.',
    'Embalagens e objetos cotidianos podem se transformar em símbolos de uma geração.',
  ],
});

const relatedSeeds = Object.freeze({
  'TV & Séries': ['series-tv', 'realities-brasileiros', 'desenhos-obrigatorios'],
  Natureza: ['animais-superpoderes', 'misterios-do-espaco', 'animais-fofos'],
  Jogos: ['jogos-videogame', 'videogames-consoles', 'jogos-celular'],
  Produtos: ['chocolates-brasil', 'salgadinhos', 'presentes-aniversario'],
});

function relatedFor(item) {
  const peers = definitions.filter((candidate) => candidate.category === item.category);
  const index = peers.indexOf(item);
  const related = [];
  for (let offset = 1; offset < peers.length && related.length < 3; offset += 1) {
    related.push(peers[(index + offset) % peers.length].id);
  }
  for (const id of relatedSeeds[item.category] || []) {
    if (related.length === 3) break;
    if (!related.includes(id)) related.push(id);
  }
  return related;
}

if (definitions.length !== 61) throw new Error(`Expected 61 rankings, found ${definitions.length}`);
if (new Set(definitions.map((item) => item.id)).size !== definitions.length) {
  throw new Error('Batch 7 contains duplicate ranking ids');
}
for (const item of definitions) {
  if (!item.image) throw new Error(`Missing cover for ${item.id}`);
  if (item.options.length !== 20 || new Set(item.options).size !== 20) {
    throw new Error(`${item.id} must contain 20 distinct options`);
  }
}

const createdAt = Date.parse('2026-08-25T10:00:00.000Z');
const batch = definitions.map((item, rankingIndex) => ({
  id: item.id,
  category: item.category,
  question: item.question,
  image_url: item.image,
  baseline_votes: 0,
  is_active: true,
  created_at: new Date(createdAt + rankingIndex * 1000).toISOString(),
  opts: item.options.map((label, optionIndex) => ({
    label,
    position: optionIndex + 1,
    baseline_score: 0,
  })),
}));

const editorial = Object.fromEntries(
  definitions.map((item) => [
    item.id,
    {
      about: `${item.focus} A ordem não pretende ser uma resposta oficial: ela combina memória, gosto pessoal e impacto cultural para que a comunidade do TOPO decida o resultado.`,
      facts: factsByCategory[item.category],
      related: relatedFor(item),
    },
  ]),
);

await Promise.all([
  writeFile(
    new URL('../data/rankings-batch-7.json', import.meta.url),
    `${JSON.stringify(batch, null, 2)}\n`,
  ),
  writeFile(
    new URL('../editorial-15.js', import.meta.url),
    `Object.assign(editorial, ${JSON.stringify(editorial, null, 2)});\n`,
  ),
]);

console.log(`Batch 7 generated: ${batch.length} rankings and ${batch.length * 20} options.`);
